### ISSUE TITLE
Posting a comment results in an error after inactivity

### ISSUE THREAD

**Issue by BartVB** [flarum/framework#3381]
## Bug Report

**Current Behavior**
When reading a topic and replying a day later posting the reply will result in a "Something went wrong" error. You need to copy, reload, hit the 'yes reload' prompt from the browser and paste to reply.

**Steps to Reproduce**
1. Open a topic where you can reply
2. Go to sleep
3. Write a reply
4. Hit 'post reply'

**Expected Behavior**
Flarum should update the CSRF in the background if there is still an active session.

**Comment by davwheat** [comment]
I'm sure we had an issue for this _somewhere_ I can't seem to find it.

I've made a concept extension to implement this (which I haven't really tested) here: https://github.com/davwheat/flarum-session-keepalive

It might not even need the frontend logic to update the CSRF in the session, since presumably Flarum already does this.

**Comment by SychO9** [comment]
We'll keep it as an extension for now.
