### ISSUE TITLE
Fix for mentions when using nicknames

### ISSUE THREAD

**Issue by iamdarkle** [flarum/framework#3505]
I think this should be considered a bug, when using nicknames the mentions take the name of the nickname instead of the user which is confusing both in discussions and when mentioning a user, as if users use the same name it is not easy to identify a user at a glance so I think there is no point in that.

On the other hand I don't know what you think but I think it would be nice to include the user @example in the user profile to also be able to easily identify which is the username, I don't know if you would consider this as a proposition, but it would be a good quality change for the nickname integration as it happens in most platforms when using nicknames/usernames. If you like I can make a issue with the explanation and places where I think it would be good to add the @ with images, if not I will make a proposal in discuss.

**Comment by SychO9** [comment]
It's wanted behavior, the **display name** is what's shown everywhere as the user's name instead of the username. Mentions do the same, they show the user's **display name**. Whether it be the posts or the profile, the display name is always what's shown.

Could you please clarify a bit further about the confusion?
