### ISSUE TITLE
Clicking load more shows the same discussions again

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3546]
### Current Behavior

Clicking load more on the index shows the same already loaded lit of discussions (page).

### Steps to Reproduce

1. Go to https://nightly.flarum.site/
2. Click load more
3. Notice same discussions duplicated.

### Expected Behavior

Should show next page of discussion list.

### Environment

- Flarum version: 1.4.0

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

Looking at the xhr, page offset seems to be `NaN`

**Comment by dsevillamartin** [comment]
This is because `getNextPageNumber` is returning `NaN`.
Both `this.pages[<last>].number` and `this.location.page` are `NaN` for some reason.

![image](https://user-images.githubusercontent.com/6401250/179774971-34bf72f4-dd89-4e27-a21e-781432422b35.png)


https://github.com/flarum/framework/blob/379c06332a0789b892b0426b3eb8be24bd557db4/framework/core/js/src/common/states/PaginatedListState.ts#L218-L226

**Comment by SychO9** [comment]
very likely from recent ts conversions https://github.com/flarum/framework/pull/3536/files#diff-c008d8ab07e15e90414eae6e2d680c8616b06895fe01eca0112e59f503c51f03R46
