### ISSUE TITLE
Tag displays as deleted once it's removed from a conversation

### ISSUE THREAD

**Issue by orschiro** [flarum/framework#3620]
### Current Behavior

One of our tags shows as deleted once it's removed from a conversation.

### Steps to Reproduce

1. Go to https://community.sheetgo.com/d/209-barcode-scanner/6
2. Remove the tag "fixed" from the conversation

### Expected Behavior

It should read "...removed the fixed tag".

Instead it's reading "...removed the Deleted tag".

### Screenshots

Video: https://drive.google.com/file/d/1QrZzd42RdtJlfjH_RllfppRKUfO-wcvP/view?usp=drivesdk

### Environment

Flarum 1.4.0 hosted at Free Flarum.

### Additional Context

Thanks for your help!

**Comment by luceos** [comment]
This is caused by the fact that tags are now no longer globally loaded and available in the JS store from the get-go. I don't know how to easily solve this, because we don't keep track of tags removed from the discussion. We'd probably need to change how event posts for Tags are stored so that tags that are mutated are a relation and can be included in the json payload.

🤔

**Comment by SychO9** [comment]
Tag mentions feature would actually solve this. The event post would have the tags attached as mentions which can then easily be loaded. Sasha first mentioned the idea on discuss https://discuss.flarum.org/d/31426-mentioning-tags-within-posts/10
