### ISSUE TITLE
Opening discussions becomes extremely slow when loading a lot of discussions.

### ISSUE THREAD

**Issue by iamdarkle** [flarum/framework#3823]
### Current Behavior

I've been noticing this for a few days now, it's especially easy if you use infinite scroll (without having to click on a button) because this way when you want to open a discussion after scrolling for a while it's really slow (also going back from that same discussion to the index), is there a reason why this happens? Opening any of the first 20 discussions is extremely fast, but from there on it's slowly getting worse and worse.

### Steps to Reproduce

1. Go to the discussion index and start loading discussions.
2. After a while you will start to notice that opening discussions and going back to continue loading new discussions is getting slower and slower.

### Expected Behavior

It should be able to load quickly despite loading more discussions(?). I'm not sure if there's a technical reason for this, and if so, what the expected behaviour might be.

### Environment

- Flarum version: 1.7.2
- Website URL: https://discuss.flarum.org/

**Comment by SychO9** [comment]
I don't see anything in core that could slow things down for specifically more discussion pages. I don't notice anything myself when doing so.

Either you are referring to really digging deep into pages in a very very large community, in which case it's possibly the effect of MySQL having to go through a higher `offset` in large data.

Or some extensions are adding more load which can usually be fixed in those extension when the bottleneck is found.

I'm closing this as it isn't clear that there is anything actionable on core.
